language: php

os:
  - linux

dist: bionic

services:
  - mysql

addons:
  postgresql: "9.6"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3

env:
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

jobs:
  include:
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14.2.0
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install --no-init

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
